pipeline{
    agent any
    stages{
        // stage("Pre-build actions"){
        //     steps{
        //         echo "Stopping and removing previous containers and images..."
        //         echo "OK"
        //     }
        // }
        stage("Building image"){
            steps{
                echo "Building app image..."
                sh "docker build -t maximus7022/laravel-app:1.${BUILD_NUMBER} ."
                echo "OK"
            }
        }
        stage("DockerHub Authentication"){
            steps{
                echo "Logging to DockerHub..."
                withCredentials([usernamePassword(credentialsId: 'DockerHub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''docker login -u $USERNAME -p $PASSWORD'''
                }
                echo "OK"
            }
        }
        stage("Publishing to DockerHub"){
            steps{
                echo "Pushing to DockerHub..."
                sh "docker push maximus7022/laravel-app:1.${BUILD_NUMBER}"
                echo "OK"
            }
        }
        stage("Cleaning up"){
            steps{
                echo "Removing unused containers and images..."
                sh "docker system prune --volumes -f"
                echo "OK"
            }
        }
        // stage("Running app"){
        //     steps{
        //         echo "Running container..."
        //         sh "docker-compose up -d"
        //     }
        // }
    }
}