pipeline{
    agent any
    stages{
        stage("Pre-build actions"){
            steps{
                echo "Stopping and removing previous containers and images..."
                sh "docker-compose down"
                sh "docker rmi laravel-app-img"
                echo "OK"
            }
        }
        stage("Building image"){
            steps{
                echo "Building app image..."
                sh "docker-compose build"
                sh "docker tag laravel-app-img maximus7022/laravel-app"
                echo "OK"
            }
        }
        stage("Publishing to DockerHub"){
            steps{
                echo "Logging to DockerHub..."
                withCredentials([usernamePassword(credentialsId: 'DockerHub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''docker login -u $USERNAME -p $PASSWORD'''
                }
                echo "OK"
            }
        }
        stage("Pushing to DockerHub"){
            steps{
                sh "docker push maximus7022/laravel-app:1.${BUILD_NUMBER}"
            }
        }
        // stage("Running app"){
        //     steps{
        //         echo "Running container..."
        //         sh "docker-compose up -d"
        //     }
        // }
    }
}